name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run unit tests
      run: mvn test

    - name: Build Docker image
      run: |
        docker build -t java-encryptor .

    - name: Verify Docker run
      run: |
        echo "Test run inside container:"
        echo "This is a secret message" > input.txt
        docker run --rm -v "$(pwd)":/data java-encryptor -e -i /data/input.txt -o /data/output.enc -p testpass
        ls -lh output.enc
